blueprint: ubuntu2204-ubuntu2204
ubuntu2:
  playbook: ubuntu2.yml
  command:
    - "sleep 180"
    - "python /opt/CVE-2021-22205/poc.py http://ubuntu1:8080 \"touch /tmp/success\""
ubuntu1:
  playbook: ubuntu1.yml
  command: 
    - "ls /tmp/success"
