---
- name: Install CVE-2021-22205 PoC for GitLab Pre-Auth Remote Command Execution
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes


    - name: Install software-properties-common
      apt:
        name: software-properties-common
        state: present

    - name: Add deadsnakes PPA
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present


    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        - docker-compose-v2
        
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - name: Create /opt/CVE-2021-22205
      file:
        path: /opt/CVE-2021-22205
        state: directory

    - name: Copy CVE-2021-22205
      ansible.builtin.copy:
        src: ./data/
        dest: /opt/CVE-2021-22205/
      
    - name: Load GitLab Docker image
      command: docker load -i /opt/CVE-2021-22205/gitlab-13.10.1.tar

    - name: Start Docker Compose services
      command: docker compose up -d --build
      args:
        chdir: /opt/CVE-2021-22205

