---
- name: Install CVE-2012-2122 environment
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install MySQL server
      apt:
        name: mysql-client
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        - docker-compose-v2

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"

    - name: Create /opt/CVE-2012-2122
      file:
        path: /opt/CVE-2012-2122
        state: directory

    - name: Copy CVE-2012-2122
      ansible.builtin.copy:
        src: ./data/
        dest: /opt/CVE-2012-2122

    - name: Start Docker Compose services
      command: docker compose up -d
      args:
        chdir: /opt/CVE-2012-2122


