---
- name: Install mysql Authentication bypass vulnerability (CVE-2012-2122)
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create /opt/CVE-2012-2122
      file:
        path: /opt/CVE-2012-2122
        state: directory

    - name: Copy CVE-2012-2122
      ansible.builtin.copy:
        src: ./data/
        dest: /opt/CVE-2012-2122/

    - name: Install MySQL client
      apt:
        name: mysql-client
        state: present

    - name: Load Docker image
      community.docker.docker_image:
        name: vulhub/mysql:5.5.23
        load_path: /opt/CVE-2012-2122/mysql.tar
        source: load
        state: present

    - name: Run mysql Docker container
      community.docker.docker_container:
        name: mysql
        image: vulhub/mysql:5.5.23
        state: started
        ports:
          - "3306:3306"