---
- name: Install CVE-2018-10933 libssh vulnerable docker
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        - docker-compose-v2
        
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"

    - name: Create /opt/LIBSSH
      file:
        path: /opt/LIBSSH
        state: directory

    - name: Copy dockerfile
      ansible.builtin.copy:
        src: ./data/docker-compose.yml
        dest: /opt/LIBSSH

    - name: Start Docker Compose services
      command: docker compose up -d --build
      args:
        chdir: /opt/LIBSSH

    - name: Create /opt/exploit
      file:
        path: /opt/exploitcode
        state: directory
      
    - name: Copy exploit to /opt/
      ansible.builtin.copy:
        src: ./data/exploit.py
        dest: /opt/exploitcode/

    - name: Install pip and venv
      apt:
        name:
          - python3-pip
        state: present
        update_cache: yes

    - name: Upgrade pip
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Install paramiko
      ansible.builtin.command: "pip install paramiko"
      become: yes
