---
- name: Install vulnerable wordpress
  hosts: all
  become: yes

  tasks:
    - name: update package index
      apt:
        update_cache: yes

    - name: create wordpress directory
      file:
        path: /tmp/wordpress-vuln
        state: directory

    - name: create plugins directory
      file:
        path: /tmp/wordpress-vuln/plugins
        state: directory

          #- name: copy wordpress tar files
      #copy:
      #src: ./data/wordpress.tar
          #dest: /tmp/wordpress-vuln

    - name: Copy docker-compose.yml
      copy:
        src: ./data/docker-compose.yml
        dest: /tmp/wordpress-vuln/docker-compose.yml

    - name: Copy ex
      copy:
        src: ./data/ex.py
        dest: /tmp/wordpress-vuln/ex.py

    - name: Extract WordPress files
      unarchive:
        src: ./data/wordpress.tar
        dest: /tmp/wordpress-vuln/

    - name: extract duplicator plugin
      unarchive:
        src: ./data/duplicator.tar
        dest: /tmp/wordpress-vuln/plugins


    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        - docker-compose-v2

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - name: Start Docker containers
      command: docker compose up -d --build
      args:
        chdir: /tmp/wordpress-vuln

    - name: Verify plugin activation
      command: >
        docker compose exec wp-cli wp plugin status duplicator --path=/var/www/html --allow-root
      args:
        chdir: /tmp/wordpress-vuln


