- name: Setup Docker 18.09.1-ce
  hosts: all
  become: yes  # Use sudo to install packages
  tasks:

    - name: Remove any existing Docker installations
      apt:
        name: docker*
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker from converted .deb file
      apt:
        deb: "./data/docker-ce-cli_18.09.1~3-0~ubuntu-bionic_amd64.deb"
      become: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      failed_when: "'18.09.1' not in docker_version.stdout"
      changed_when: false

    - name: Display Docker version
      debug:
        msg: "Installed Docker version: {{ docker_version.stdout }}"

    - name: Copy exploit.go file to target machine
      copy:
        src: ./data/exploit.go
        dest: /tmp/exploit.go
        mode: '0755'

    - name: Compile exploit.go
      command: go build -o /tmp/exploit /tmp/exploit.go
      args:
        chdir: /tmp

