- name: Nginx server
  hosts: all
  become: true
  tasks:
    - name: Copy openssl
      ansible.builtin.copy:
        src: ./data/openssl-1.0.1f.tar.gz
        dest: /opt/openssl-1.0.1f.tar.gz
        checksum: 9ef09e97dfc9f14ac2c042f3b7e301098794fc0f
    - name: Copy nginx
      ansible.builtin.copy:
        src: ./data/nginx-1.6.0.tar.gz
        dest: /opt/nginx-1.6.0.tar.gz
        checksum: 00eed38652d2cee36cc91a395f6703584658bb23
    - name: Unpack openssl
      ansible.builtin.unarchive:
        src: /opt/openssl-1.0.1f.tar.gz
        remote_src: true
        dest: /opt/
    - name: Unpack nginx
      ansible.builtin.unarchive:
        src: /opt/nginx-1.6.0.tar.gz
        remote_src: true
        dest: /opt/
    - name: Build nginx
      ansible.builtin.shell: |
        cd /opt/nginx-1.6.0
        ./configure --prefix=/opt/vuln --with-openssl=../openssl-1.0.1f --with-http_ssl_module --without-http_rewrite_module
        make
        make install
    - name: Copy default.conf
      ansible.builtin.copy:
        src: ./data/default.conf
        dest: /opt/vuln/conf/nginx.conf
    - name: Copy certificate
      ansible.builtin.copy:
        src: ./data/linux.crt
        dest: /opt/vuln/conf/crt
    - name: Copy key
      ansible.builtin.copy:
        src: ./data/linux.key
        dest: /opt/vuln/conf/key
    - name: Start nginx
      ansible.builtin.shell: /opt/vuln/sbin/nginx
