blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  playbook: ubuntu1.yml
  command:
    - "php -S 0.0.0.0:9999 -f /var/www/html"
ubuntu2:
  playbook: ubuntu2.yml
  command:
    - "/var/www/generate_data.sh %ubuntu1%"
    - "cd /var && docker compose up -d --build"
