---
- name: Install CVE-2016-1897 environment
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        - docker-compose-v2

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"

    - name: Create /var/www
      file:
        path: /var/www
        state: directory

    - name: Copy docker-compose
      ansible.builtin.copy:
        src: ./data/docker-compose.yml
        dest: /var/docker-compose.yml

    - name: Copy www/index.php
      ansible.builtin.copy:
        src: ./data/www/index.php
        dest: /var/www/index.php

    - name: Copy www/6215ca35009ea.mp4
      ansible.builtin.copy:
        src: ./data/www/6215ca35009ea.mp4
        dest: /var/www/6215ca35009ea.mp4

    - name: Copy www/generate_data.sh
      ansible.builtin.copy:
        src: ./data/www/generate_data.sh
        dest: /var/www/generate_data.sh

