---
- name: Install + test CVE-2021-3156 (sudo privilege escalation)
  hosts: ubuntu
  become: yes
  vars:
    sudo_version: "1.8.31"
    install_dir: "/opt/sudo"
    source_dir: "/opt/sudo/sudo-{{ sudo_version }}"
    exploit_dir: "/opt/exploit"

  tasks:

    # Create the installation directory for sudo
    - name: Create sudo installation directory
      file:
        path: "{{ install_dir }}"
        state: directory

    # Copy the vulnerable sudo tar file to the target VM
    - name: Copy vulnerable sudo tar file
      copy:
        src: "./data/sudo-{{ sudo_version }}.tar.gz"
        dest: "{{ install_dir }}/sudo-{{ sudo_version }}.tar.gz"

    # Extract the tar file
    - name: Extract vulnerable sudo tar file
      unarchive:
        src: "./data/sudo-{{ sudo_version }}.tar.gz"
        dest: "{{ install_dir }}"

    # Create hacker user
    - name: Create hacker user
      ansible.builtin.user:
        name: hacker
        uid: 1002
        create_home: yes

    # Ensure Python3 is installed
    - name: Install Python3
      apt:
        name: python3
        state: present

    # Create exploit directory
    - name: Create exploit directory
      file:
        path: "{{ exploit_dir }}"
        state: directory

    # Copy exploit script to the target machine
    - name: Copy exploit script
      copy:
        src: "./data/sudo_exploit.py"
        dest: "{{ exploit_dir }}/sudo_exploit.py"
        mode: "0755"
        owner: hacker

    # Create a vulnerable file for testing privilege escalation
    - name: Create a protected file for testing
      copy:
        src: "./data/secret.txt"
        dest: "/home/hacker/secret.txt"
        mode: "0600"
        owner: hacker
